project:
  type: website

website:
  title: "Datasets"
  navbar:
    back-to-top-navigation: true
    background: "#457E76"

  sidebar:
    style: "docked"
    background: "#DDEEEC"
    logo: img/LogoINE.svg
    logo-alt: Logo INE
    contents: auto

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

